AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false

Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
